name: card_shuffle
description: A Flutter Tarot Shuffle & Reading App (Moonworld-style riffle and deal)
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cards.json
    - assets/tarot/cards/card_back.svg
  # Fonts removed from manifest to avoid missing-asset build errors.
  # Add font files to assets/fonts/ and re-enable here if you want custom fonts.
